### ISSUE TITLE
Question about the edge dofs

### ISSUE THREAD

**Issue by liangqx-hku** [csyzzkdcz/WrinkledTensionFields#1]
Hi there,

Thanks for sharing your awesome work!

I have a question about the initial values of the edge dofs for the rest curved shell. For the initial curved shell problem, how to set the initial values for the edge dofs? I think it's difficult to compute the edge dof \phi in the initial configuration, could you give some suggestions?
Many thanks!

Best,
Leung

**Comment by zhenchen-jay** [comment]
To confirm, you are asking the edge dof for the base mesh, not for the wrinkle variables. If this is the case, this edge dof is just the angle of how to fine-tuning the midedge normal for a better bending model. If you use mideedgeaverage formula, you can ignore that. Otherwise you can initialize as all zeros.

**Comment by liangqx-hku** [comment]
Thx!
